version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backnet

  backend:
    build: ./back-end
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backnet

  frontend:
    build: ./front-end
    ports:
      - "80:80"
    networks:
      - backnet
networks:
  backnet:
    driver: bridge